export const SCENARIOS = [
  {
    id: 'cbi_scam',
    name: 'Fake CBI Arrest (Scam)',
    category: 'Scam',
    description: 'Impersonation of CBI Cyber Crime official claiming drug money laundering.',
    isAiVoice: false,
    deepfakeScore: 0.04,
    sentences: [
      'Attention! This is the CBI Cyber Crime Headquarters in New Delhi.',
      'We have intercepted an offshore account under your Aadhaar number holding 2.5 crore rupees linked to illegal drug cartel finances.',
      'A Supreme Court warrant of arrest has been prepared in your name for immediately jail custody.',
      'You are ordered to stay in this room, keep your camera active, and do not contact family members or disconnect this call.',
      'This is a confidential national security inspection.',
      'You must transfer a verification security deposit of fifty thousand rupees to the RBI verified account right now.',
    ],
  },
  {
    id: 'customs_deepfake_scam',
    name: 'Customs Seizure (Scam + AI Voice)',
    category: 'Deepfake Scam',
    description: 'Impersonation of Customs officer seizing a package containing narcotics. Uses AI cloned voice.',
    isAiVoice: true,
    deepfakeScore: 0.96,
    sentences: [
      'Hello, I am calling from Mumbai Airport Customs Cargo division.',
      'An international courier parcel containing your fake credit cards, illegal passports, and MDMA drugs has been seized.',
      'Under the NDPS Act, you face immediate jail and court hearing within thirty minutes.',
      'You must lock your door and do not reveal this secret audit investigation to anyone else.',
      'Our deputy commissioner requires you to declare your bank balance and liquidate funds to avoid immediate arrest.',
    ],
  },
  {
    id: 'genuine_bank',
    name: 'Bank Transaction (Genuine)',
    category: 'Genuine',
    description: 'Typical credit card validation check from a real financial representative.',
    isAiVoice: false,
    deepfakeScore: 0.02,
    sentences: [
      'Hello, this is standard customer verification from your bank security desk.',
      'We noticed a suspicious transaction of forty-five thousand rupees at an e-commerce vendor.',
      'We have temporarily frozen the card for security. We do not ask for any OTP, passwords, or netbanking credentials.',
      'Please confirm if you attempted this transaction or if we should issue a replacement card.',
    ],
  },
  {
    id: 'genuine_courier',
    name: 'Courier Delivery (Genuine)',
    category: 'Genuine',
    description: 'Standard delivery agent confirming arrival status.',
    isAiVoice: false,
    deepfakeScore: 0.08,
    sentences: [
      'Hello sir, I am a courier dispatch executive calling from BlueDart office.',
      'I have arrived outside your apartment block gate with a parcel package.',
      'Could you please confirm if you are available at home to sign for this package?',
      'No security code or payment is needed, just a physical confirmation. Thank you.',
    ],
  },
]
